### ISSUE TITLE
error while converting weights in new conda env

### ISSUE THREAD

**Issue by romanoss** [zzh8829/yolov3-tf2#10]
(yolov3-tf2) C:\Users\roman\ml\yolov3-tf2>python convert.py --weights ./data/yolov3-tiny.weights --output ./checkpoints/yolov3-tiny.tf --tiny
Traceback (most recent call last):
  File "convert.py", line 4, in <module>
    from yolov3_tf2.models import YoloV3, YoloV3Tiny
  File "C:\Users\roman\ml\yolov3-tf2\yolov3_tf2\models.py", line 2, in <module>
    import tensorflow as tf
  File "C:\Users\roman\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\roman\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\roman\AppData\Roaming\Python\Python36\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\roman\AppData\Roaming\Python\Python36\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: Procedure not found

**Comment by zzh8829** [comment]
it looks to me conda env did not activate properly, can you try this article https://docs.anaconda.com/anaconda/install/verify-install/
