### ISSUE TITLE
Failed to find any matching files for ./checkpoints/yolov3.tf

### ISSUE THREAD

**Issue by jkiani64** [zzh8829/yolov3-tf2#109]
I get this error. Could you please help me to solve it?

2019-11-24 18:46:00.689586: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-24 18:46:00.746495: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe63b527850 executing computations on platform Host. Devices:
2019-11-24 18:46:00.746532: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "detect.py", line 61, in <module>
    app.run(main)
  File "/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "detect.py", line 33, in main
    yolo.load_weights(FLAGS.weights)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 181, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1143, in load_weights
    pywrap_tensorflow.NewCheckpointReader(filepath)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 873, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
  File "/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 885, in __init__
    this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoints/yolov3.tf

**Comment by NiklasWilson** [comment]
@jkiani64 You have to download the weights and run the convert script.

# yolov3
wget https://pjreddie.com/media/files/yolov3.weights -O data/yolov3.weights
python convert.py

# yolov3-tiny
wget https://pjreddie.com/media/files/yolov3-tiny.weights -O data/yolov3-tiny.weights
python convert.py --weights ./data/yolov3-tiny.weights --output ./checkpoints/yolov3-tiny.tf --tiny

**Comment by zzh8829** [comment]
right, you can also see the convert instruction in readme
