### ISSUE TITLE
不能训练

### ISSUE THREAD

**Issue by Monkeone** [zzh8829/yolov3-tf2#119]
2019-12-07 23:46:26.566296: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: {{function_node __inference_Dataset_map_<lambda>_14279}} Feature: image/filename (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
2019-12-07 23:46:26.566592: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Feature: image/filename (data type: string) is required but could not be found.
2019-12-07 23:46:26.725021: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: {{function_node __inference_Dataset_map_<lambda>_14279}} Feature: image/filename (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_2]]
2019-12-07 23:46:26.730265: I tensorflow/core/profiler/lib/profiler_session.cc:184] Profiler session started.
2019-12-07 23:46:26.734688: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cupti64_100.dll'; dlerror: cupti64_100.dll not found
2019-12-07 23:46:26.734884: W tensorflow/core/profiler/lib/profiler_session.cc:192] Encountered error while starting profiler: Unavailable: CUPTI error: CUPTI could not be loaded or symbol could not be found.

      1/Unknown - 17s 17s/stepW1207 23:46:26.748831  5384 callbacks.py:1824] Reduce LR on plateau conditioned on metric `val_loss` which is not available. Available metrics are: lr

W1207 23:46:26.748831  5384 callbacks.py:1250] Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: 
Epoch 00001: saving model to checkpoints/yolov3_train_1.tf

      1/Unknown - 28s 28s/step2019-12-07 23:46:38.263195: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 0 kernel records, 0 memcpy records.
2019-12-07 23:46:38.276532: E tensorflow/core/platform/default/device_tracer.cc:70] CUPTI error: CUPTI could not be loaded or symbol could not be found.
Traceback (most recent call last):
  File "D:/yolov3-tf2-master/train.py", line 180, in <module>
    app.run(main)
  File "D:\新建文件夹\python\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "D:\新建文件夹\python\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "D:/yolov3-tf2-master/train.py", line 175, in main
    validation_data=val_dataset)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 520, in _call
    return self._stateless_fn(*args, **kwds)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\eager\function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\eager\function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)
  File "D:\新建文件夹\python\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  {{function_node __inference_Dataset_map_<lambda>_14279}} Feature: image/filename (data type: string) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]] [Op:__inference_distributed_function_39847]

Function call stack:
distributed_function

**Comment by zzh8829** [comment]
Please see https://github.com/zzh8829/yolov3-tf2/blob/master/docs/training_voc.md for a updated tutorial on training, let me know if it works

**Comment by Monkeone** [comment]
it works well in my computer,thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zihao Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月21日(星期六) 下午3:16
收件人:&nbsp;"zzh8829/yolov3-tf2"<yolov3-tf2@noreply.github.com&gt;;
抄送:&nbsp;"1270843624"<1270843624@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zzh8829/yolov3-tf2] 不能训练 (#119)




Please see https://github.com/zzh8829/yolov3-tf2/blob/master/docs/training_voc.md for a updated tutorial on training, let me know if it works
