### ISSUE TITLE
Error training custom object detection

### ISSUE THREAD

**Issue by evandrix** [zzh8829/yolov3-tf2#12]
```
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 49, in main
    model = YoloV3(FLAGS.size, training=True)
  File "/github.com/zzh8829/yolov3-tf2/yolov3_tf2/models.py", line 210, in YoloV3
    x = YoloConv(128, name='yolo_conv_2')((x, x_36))
  File "/github.com/zzh8829/yolov3-tf2/yolov3_tf2/models.py", line 103, in yolo_conv
    x = Concatenate()([x, x_skip])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 594, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1713, in _maybe_build
    self.build(input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 290, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/merge.py", line 392, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 36, 36, 128), (None, 37, 37, 256)]
```

**Comment by zzh8829** [comment]
have you tried training with python3, i haven't had much experience with 2.7
