### ISSUE TITLE
Invalid argument: Expected image (JPEG, PNG, or GIF)-Error while training on custom dataset

### ISSUE THREAD

**Issue by MarBra110** [zzh8829/yolov3-tf2#15]
Hi there, 
I am currently trying to train on my custom dataset. I have created a .tfrecord-file which looks reasonable to me. However, when I run train.py the following error message occurs directly after having printed `Epoch 1/100`: 

`2019-05-20 22:19:39.735116: W tensorflow/core/framework/op_kernel.cc:1431] OP_REQUIRES failed at iterator_ops.cc:988 : Invalid argument: Expected image (JPEG, PNG, or GIF), got unknown format starting with '/9j/4AAQSkZJRgAB'
	 [[{{node DecodeJpeg}}]]
Traceback (most recent call last):
  File "C:/Users/Marcel/.../yolov3-tf2/train.py", line 184, in <module>
    app.run(main)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:/Users/Marcel/Desktop/Uni/6.Semester/Projektarbeit/YOLO/asia_repo/yolov3-tf2/train.py", line 176, in main
    validation_data=val_dataset)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 791, in fit
    initial_epoch=initial_epoch)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1515, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 213, in model_iteration
    batch_data = _get_next_batch(generator, mode)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 355, in _get_next_batch
    generator_output = next(generator)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 556, in __next__
    return self.next()
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 585, in next
    return self._next_internal()
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 577, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 1983, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with '/9j/4AAQSkZJRgAB'
	 [[{{node DecodeJpeg}}]] [Op:IteratorGetNextSync]`

Comparing the given "start of the unknown data" (/9j/4AAQSkZJRgAB) with the .tfrecord-file it becomes clear, that it is the start of the encoded image: 
`features {
  feature {
    key: "image/encoded"
    value {
      bytes_list {
        value: "/9j/4AAQSkZJRgABAQAAAQABAAD..."
     }
   } ... }`

So I think my .tfrecord-file is not the problem in this case but rather I am somewhere missing a decoding of the encoded image. I also already checked if my files are in some way corrupted, but I am pretty sure that they are fine. Used google and stackoverflow but these did not reveal the answer to my problem neither. Thus, I am stuck and cannot think of another reason for this error. 
Did anyone else experience the same problem and can help me find the source of this error?

**Comment by zzh8829** [comment]
Referencing this answer: https://stackoverflow.com/a/38784801/5395495

Looks like your image/encoded field contains base64 encoded jpeg images.
You will want to re-create the dataset with raw byte encoded images.

**Comment by MarBra110** [comment]
You are absolutely right. The use of base64 is completely obsolete, just calling image.read() to get the encoded image is enough. 
Thanks for the fast response!
