### ISSUE TITLE
weird error after one epoch of training 

### ISSUE THREAD

**Issue by eliwilner** [zzh8829/yolov3-tf2#156]
Hi,

I'm running the train.py with my own dataset where after one epoch I get the following error:

08 - yolo_output_2_loss: 747.91192020-01-14 02:49:00.109261: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: {{function_node __inference_Dataset_map_<lambda>_14255}} Paddings must be non-negative: 0 -60
	 [[{{node Pad}}]]
	 [[IteratorGetNext]]
	 [[loss/yolo_output_2_loss/Shape_1/_16]]
2020-01-14 02:49:00.109338: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: {{function_node __inference_Dataset_map_<lambda>_14255}} Paddings must be non-negative: 0 -60
	 [[{{node Pad}}]]
	 [[IteratorGetNext]]
    138/Unknown - 164s 1s/step - loss: 912.3278 - yolo_output_0_loss: 45.6427 - yolo_output_1_loss: 107.8608 - yolo_output_2_loss: 747.9119WARNING:tensorflow:Reduce LR on plateau conditioned on metric `val_loss` which is not available. Available metrics are: loss,yolo_output_0_loss,yolo_output_1_loss,yolo_output_2_loss,lr
W0114 02:49:00.123334 139863391131456 callbacks.py:1824] Reduce LR on plateau conditioned on metric `val_loss` which is not available. Available metrics are: loss,yolo_output_0_loss,yolo_output_1_loss,yolo_output_2_loss,lr
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,yolo_output_0_loss,yolo_output_1_loss,yolo_output_2_loss,lr
W0114 02:49:00.123596 139863391131456 callbacks.py:1250] Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,yolo_output_0_loss,yolo_output_1_loss,yolo_output_2_loss,lr

Epoch 00001: saving model to checkpoints/yolov3_train_1.tf
    138/Unknown - 167s 1s/step - loss: 912.3278 - yolo_output_0_loss: 45.6427 - yolo_output_1_loss: 107.8608 - yolo_output_2_loss: 747.9119Traceback (most recent call last):
  File "train.py", line 193, in <module>
    app.run(main)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 188, in main
    validation_data=val_dataset)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 487, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/ubuntu/anaconda3/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  {{function_node __inference_Dataset_map_<lambda>_14255}} Paddings must be non-negative: 0 -60
	 [[{{node Pad}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument:  {{function_node __inference_Dataset_map_<lambda>_14255}} Paddings must be non-negative: 0 -60
	 [[{{node Pad}}]]
	 [[IteratorGetNext]]
	 [[loss/yolo_output_2_loss/Shape_1/_16]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_50725]

Function call stack:
distributed_function -> distributed_function

Does anyone know what it means?

**Comment by KaneFury** [comment]
I had a similar error. I just updated the repo (redownloaded it) and it worked.

**Comment by RaccoonForever** [comment]
I had a similar error.
I corrected it by checking my data in tfrecords to have no prediction boxes with a coordinate greater than 1 and lower than 0.

**Comment by Eve66666** [comment]
> I had a similar error.
> I corrected it by checking my data in tfrecords to have no prediction boxes with a coordinate greater than 1 and lower than 0.

Hi, What should I do specifically?

**Comment by RaccoonForever** [comment]
I suggest you :
- Either write a script to check all your boxes to be between 1 and 0
- Either investigate why do you have some values that are above 1 and lower than 0 and correct it

I can't write the code for you :D

**Comment by funkydude755** [comment]
I solved this by removing the smallest bounding boxes from my data-set

**Comment by Hsengiv2000** [comment]
I had the same problem. This is because the max number of detections allowed in an image is 100, else youll get the padding failed error. So fix this by changing the flags parameter in models.py

Just change line 25 in models.py, this file is located inside the yolov3_tf2 folder. Replace the 100 with whatver is the max number of bounding boxes you have in the image(take a higher number)
