### ISSUE TITLE
Invalid argument:  Paddings must be non-negative: 0 -49

### ISSUE THREAD

**Issue by pythonlessons** [zzh8829/yolov3-tf2#226]
Gathered around 14k training images for 7 classes. Trained with following:
`

> python train.py \
> 	--dataset ./OID/Dataset/train.record \
> 	--val_dataset ./OID/Dataset/test.record \
> 	--classes ./OID/Dataset/Dataset_names.txt \
> 	--num_classes 8 \
> 	--mode fit \
> 	--transfer no_output \
> 	--batch_size 8 \
> 	--epochs 100 \
> 	--weights ./checkpoints/yolov3.tf \
> 	--weights_num_classes 80 

In first epoch I receive following error:

> Epoch 00001: saving model to checkpoints/yolov3_train_1.tf
>     514/Unknown - 99s 193ms/step - loss: 266.1149 - yolo_output_0_loss: 10.6977 - yolo_output_1_loss: 35.3128 - yolo_output_2_loss: 210.0261Traceback (most recent call last):
>   File "train.py", line 195, in <module>
>     app.run(main)
>   File "/home/rokas/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/home/rokas/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "train.py", line 190, in main
>     validation_data=val_dataset)
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
>     use_multiprocessing=use_multiprocessing)
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
>     total_epochs=epochs)
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
>     batch_outs = execution_function(iterator)
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
>     distributed_function(input_fn))
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
>     result = self._call(*args, **kwds)
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 599, in _call
>     return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
>     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
>     self.captured_inputs)
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
>     ctx, args, cancellation_manager=cancellation_manager))
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
>     ctx=ctx)
>   File "/home/rokas/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
>     six.raise_from(core._status_to_exception(e.code, message), None)
>   File "<string>", line 3, in raise_from
> tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
>   (0) Invalid argument:  Paddings must be non-negative: 0 -49
> 	 [[{{node Pad}}]]
> 	 [[IteratorGetNext]]
>   (1) Invalid argument:  Paddings must be non-negative: 0 -49
> 	 [[{{node Pad}}]]
> 	 [[IteratorGetNext]]
> 	 [[IteratorGetNext/_6]]
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_distributed_function_47063]
> 
> Function call stack:
> distributed_function -> distributed_function
> 
> WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-8
> W0406 09:19:23.864811 140159439697728 util.py:144] Unresolved object in checkpoint: (root).layer-8
> WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9
> W0406 09:19:23.864943 140159439697728 util.py:144] Unresolved object in checkpoint: (root).layer-9
> WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10
> W0406 09:19:23.864983 140159439697728 util.py:144] Unresolved object in checkpoint: (root).layer-10
> WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-11
> W0406 09:19:23.865016 140159439697728 util.py:144] Unresolved object in checkpoint: (root).layer-11
> WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
> W0406 09:19:23.865081 140159439697728 util.py:152] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
>

**Comment by pythonlessons** [comment]
I found that it's something with image data, but can't find what exactly
