### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -80

### ISSUE THREAD

**Issue by jacksparrow47** [zzh8829/yolov3-tf2#266]
Hi everyone,
I am facing interesting things. I am using same code for 2 diffrent datasets. One from kaggle and another is mine dataset. I am creating tfrecord files for both of datasets. But when I train or visualize datasets , all thing is right for kaggle dataset but for my dataset gives error like below.

```I0512 13:08:34.023212 140428778952576 visulize.py:28] data loaded
<ShuffleDataset shapes: ((416, 416, 3), (None, 5)), types: (tf.float32, tf.float32)>
<TakeDataset shapes: ((416, 416, 3), (None, 5)), types: (tf.float32, tf.float32)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1986, in execution_mode
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 655, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2363, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -80
	 [[{{node Pad}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./visulize.py", line 67, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./visulize.py", line 34, in main
    for image, labels in data:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 631, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 670, in next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1989, in execution_mode
    executor_new.wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -80
	 [[{{node Pad}}]]
```

When I logged the result of the below code

```dataset = load_tfrecord_dataset(fgdataset, fgclasses, fgsize)
    logging.info('data loaded')
    dataset = dataset.shuffle(512)
    print(dataset)
    data=dataset.take(1)
    print(data)

```
both of them show same thing.
<ShuffleDataset shapes: ((416, 416, 3), (None, 5)), types: (tf.float32, tf.float32)>
<TakeDataset shapes: ((416, 416, 3), (None, 5)), types: (tf.float32, tf.float32)>

Only different thing between datasets , there is a one class in kaggle dataset , nine class are in my dataset
Here is kaggle class.names

```
background
plane
```

And my class.names
```
background
0
1
2
3
4
5
6
7
```
Here is my voc2012.py

```
import time
import os
import hashlib

from absl import app, flags, logging
from absl.flags import FLAGS
import tensorflow as tf
import lxml.etree
import tqdm


flags.DEFINE_string('data_dir', '.',
                    'path to raw PASCAL VOC dataset')
flags.DEFINE_enum('split', 'val', [
                  'train', 'val'], 'specify train or val spit')
flags.DEFINE_string('output_file', './tfrecord/voc2012_val.tfrecord', 'outpot dataset')
flags.DEFINE_string('classes', './voc2012.names', 'classes file')

def build_example(annotation, class_map):
    img_path = os.path.join(
        FLAGS.data_dir, 'images', annotation['filename'])
    img_raw = open(img_path, 'rb').read()
    key = hashlib.sha256(img_raw).hexdigest()

    width = int(annotation['size']['width'])
    height = int(annotation['size']['height'])

    xmin = []
    ymin = []
    xmax = []
    ymax = []
    classes = []
    classes_text = []
    truncated = []
    views = []
    difficult_obj = []
    if 'object' in annotation:
        for obj in annotation['object']:
            difficult = bool(int(obj['difficult']))
            difficult_obj.append(int(difficult))

            xmin.append(float(obj['bndbox']['xmin']) / width)
            ymin.append(float(obj['bndbox']['ymin']) / height)
            xmax.append(float(obj['bndbox']['xmax']) / width)
            ymax.append(float(obj['bndbox']['ymax']) / height)
            classes_text.append(obj['name'].encode('utf8'))
            classes.append(class_map[obj['name']])
            truncated.append(int(obj['truncated']))
            views.append(obj['pose'].encode('utf8'))

    example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': tf.train.Feature(int64_list=tf.train.Int64List(value=[height])),
        'image/width': tf.train.Feature(int64_list=tf.train.Int64List(value=[width])),
        'image/filename': tf.train.Feature(bytes_list=tf.train.BytesList(value=[
            annotation['filename'].encode('utf8')])),
        'image/source_id': tf.train.Feature(bytes_list=tf.train.BytesList(value=[
            annotation['filename'].encode('utf8')])),
        'image/key/sha256': tf.train.Feature(bytes_list=tf.train.BytesList(value=[key.encode('utf8')])),
        'image/encoded': tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_raw])),
        'image/format': tf.train.Feature(bytes_list=tf.train.BytesList(value=['jpeg'.encode('utf8')])),
        'image/object/bbox/xmin': tf.train.Feature(float_list=tf.train.FloatList(value=xmin)),
        'image/object/bbox/xmax': tf.train.Feature(float_list=tf.train.FloatList(value=xmax)),
        'image/object/bbox/ymin': tf.train.Feature(float_list=tf.train.FloatList(value=ymin)),
        'image/object/bbox/ymax': tf.train.Feature(float_list=tf.train.FloatList(value=ymax)),
        'image/object/class/text': tf.train.Feature(bytes_list=tf.train.BytesList(value=classes_text)),
        'image/object/class/label': tf.train.Feature(int64_list=tf.train.Int64List(value=classes)),
        'image/object/difficult': tf.train.Feature(int64_list=tf.train.Int64List(value=difficult_obj)),
        'image/object/truncated': tf.train.Feature(int64_list=tf.train.Int64List(value=truncated)),
        'image/object/view': tf.train.Feature(bytes_list=tf.train.BytesList(value=views)),
    }))
    return example


def parse_xml(xml):
    if not len(xml):
        return {xml.tag: xml.text}
    result = {}
    for child in xml:
        child_result = parse_xml(child)
        if child.tag != 'object':
            result[child.tag] = child_result[child.tag]
        else:
            if child.tag not in result:
                result[child.tag] = []
            result[child.tag].append(child_result[child.tag])
    return {xml.tag: result}


def main(_argv):
    class_map = {name: idx for idx, name in enumerate(
        open(FLAGS.classes).read().splitlines())}
    logging.info("Class mapping loaded: %s", class_map)

    writer = tf.io.TFRecordWriter(FLAGS.output_file)
    image_directory=FLAGS.data_dir+"/images/"
    image_list=os.listdir(image_directory)
    logging.info("Image list loaded: %d", len(image_list))
    annots_directory=FLAGS.data_dir+"/annots/"
    for image in tqdm.tqdm(image_list):
        annotation_xml=annots_directory+image[0:image.rindex('.')]+".xml"
        annotation_xml = lxml.etree.fromstring(open(annotation_xml).read())
        annotation = parse_xml(annotation_xml)['annotation']
        tf_example = build_example(annotation, class_map)
        print(tf_example)
        writer.write(tf_example.SerializeToString())
        
    writer.close()
    logging.info("Done")


if __name__ == '__main__':
    app.run(main)


```

I dont know what can i do. any one can help me?
thanks already

**Comment by w19787** [comment]
it seems to be the class no. is greater than 80. it will cause the padding error.

**Comment by jacksparrow47** [comment]
> it seems to be the class no. is greater than 80. it will cause the padding error.

Hi w19787,
I have only 9 class. I dont think why. 
Here is a record of tf example from my dataset. I didn't see anything strange

```
features {
  feature {
    key: "image/encoded"
    value {
      bytes_list {
        value: "\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\003\350\000\000\002\274\010\002\000\000\000\363\251\002\346\000\000 
		I deleted here for limit
		6v\231\303\375U\000\000\000\000IEND\256B`\202"
      }
    }
  }
  feature {
    key: "image/filename"
    value {
      bytes_list {
        value: "train_371.png"
      }
    }
  }
  feature {
    key: "image/format"
    value {
      bytes_list {
        value: "jpeg"
      }
    }
  }
  feature {
    key: "image/height"
    value {
      int64_list {
        value: 700
      }
    }
  }
  feature {
    key: "image/key/sha256"
    value {
      bytes_list {
        value: "5426ed7c9c36b55f42073e48562d8e8f0e68c70680b9db8b6cd65fd57475334f"
      }
    }
  }
  feature {
    key: "image/object/bbox/xmax"
    value {
      float_list {
        value: 0.49799999594688416
        value: 0.49399998784065247
        value: 0.5720000267028809
        value: 0.49900001287460327
        value: 0.5040000081062317
        value: 0.5410000085830688
        value: 0.5059999823570251
        value: 0.5070000290870667
        value: 0.3179999887943268
        value: 0.49399998784065247
        value: 0.3089999854564667
        value: 0.5389999747276306
        value: 0.515999972820282
        value: 0.5410000085830688
        value: 0.546999990940094
        value: 0.4860000014305115
        value: 0.20399999618530273
        value: 0.531000018119812
        value: 0.5400000214576721
        value: 0.5960000157356262
        value: 0.6050000190734863
        value: 0.6499999761581421
        value: 0.5680000185966492
        value: 0.5720000267028809
        value: 0.5630000233650208
        value: 0.6579999923706055
        value: 0.6380000114440918
        value: 0.6129999756813049
        value: 0.609000027179718
        value: 0.6140000224113464
        value: 0.609000027179718
        value: 0.4480000138282776
      }
    }
  }
  feature {
    key: "image/object/bbox/xmin"
    value {
      float_list {
        value: 0.4830000102519989
        value: 0.47099998593330383
        value: 0.5649999976158142
        value: 0.4909999966621399
        value: 0.492000013589859
        value: 0.531000018119812
        value: 0.49399998784065247
        value: 0.4950000047683716
        value: 0.3050000071525574
        value: 0.48500001430511475
        value: 0.29899999499320984
        value: 0.531000018119812
        value: 0.5059999823570251
        value: 0.5329999923706055
        value: 0.5350000262260437
        value: 0.47699999809265137
        value: 0.19300000369548798
        value: 0.5199999809265137
        value: 0.5320000052452087
        value: 0.5899999737739563
        value: 0.5979999899864197
        value: 0.6320000290870667
        value: 0.5580000281333923
        value: 0.5619999766349792
        value: 0.5540000200271606
        value: 0.6499999761581421
        value: 0.6349999904632568
        value: 0.6100000143051147
        value: 0.6050000190734863
        value: 0.6100000143051147
        value: 0.6060000061988831
        value: 0.335999995470047
      }
    }
  }
  feature {
    key: "image/object/bbox/ymax"
    value {
      float_list {
        value: 0.704285740852356
        value: 0.6885714530944824
        value: 0.6742857098579407
        value: 0.6514285802841187
        value: 0.618571400642395
        value: 0.5985714197158813
        value: 0.595714271068573
        value: 0.5828571319580078
        value: 0.5571428537368774
        value: 0.5357142686843872
        value: 0.5314285755157471
        value: 0.508571445941925
        value: 0.4942857027053833
        value: 0.49142858386039734
        value: 0.4457142949104309
        value: 0.43142858147621155
        value: 0.38428571820259094
        value: 0.3814285695552826
        value: 0.28142857551574707
        value: 0.25285714864730835
        value: 0.25285714864730835
        value: 0.24285714328289032
        value: 0.21142856776714325
        value: 0.20571428537368774
        value: 0.19285714626312256
        value: 0.18285714089870453
        value: 0.15571428835391998
        value: 0.14428570866584778
        value: 0.14428570866584778
        value: 0.14000000059604645
        value: 0.14000000059604645
        value: 0.977142870426178
      }
    }
  }
  feature {
    key: "image/object/bbox/ymin"
    value {
      float_list {
        value: 0.691428542137146
        value: 0.6700000166893005
        value: 0.6700000166893005
        value: 0.6428571343421936
        value: 0.6085714101791382
        value: 0.5885714292526245
        value: 0.5842857360839844
        value: 0.5714285969734192
        value: 0.545714259147644
        value: 0.5242857336997986
        value: 0.522857129573822
        value: 0.5
        value: 0.48571428656578064
        value: 0.48428571224212646
        value: 0.4342857003211975
        value: 0.4228571355342865
        value: 0.37714284658432007
        value: 0.37285715341567993
        value: 0.2742857038974762
        value: 0.24857142567634583
        value: 0.24571429193019867
        value: 0.2257142812013626
        value: 0.2028571367263794
        value: 0.19857142865657806
        value: 0.18142856657505035
        value: 0.17714285850524902
        value: 0.15142856538295746
        value: 0.14142857491970062
        value: 0.14000000059604645
        value: 0.13571429252624512
        value: 0.13571429252624512
        value: 0.03999999910593033
      }
    }
  }
  feature {
    key: "image/object/class/label"
    value {
      int64_list {
        value: 1
        value: 1
        value: 1
        value: 1
        value: 1
        value: 1
        value: 1
        value: 2
        value: 1
        value: 1
        value: 8
        value: 1
        value: 1
        value: 1
        value: 1
        value: 1
        value: 4
        value: 2
        value: 1
        value: 5
        value: 1
        value: 1
        value: 1
        value: 1
        value: 1
        value: 1
        value: 5
        value: 3
        value: 3
        value: 3
        value: 3
        value: 7
      }
    }
  }
  feature {
    key: "image/object/class/text"
    value {
      bytes_list {
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "1"
        value: "0"
        value: "0"
        value: "7"
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "3"
        value: "1"
        value: "0"
        value: "4"
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "0"
        value: "4"
        value: "2"
        value: "2"
        value: "2"
        value: "2"
        value: "6"
      }
    }
  }
  feature {
    key: "image/object/difficult"
    value {
      int64_list {
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
      }
    }
  }
  feature {
    key: "image/object/truncated"
    value {
      int64_list {
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
        value: 0
      }
    }
  }
  feature {
    key: "image/object/view"
    value {
      bytes_list {
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
        value: "Unspecified"
      }
    }
  }
  feature {
    key: "image/source_id"
    value {
      bytes_list {
        value: "train_371.png"
      }
    }
  }
  feature {
    key: "image/width"
    value {
      int64_list {
        value: 1000
      }
    }
  }
}
```

**Comment by jacksparrow47** [comment]
> it seems to be the class no. is greater than 80. it will cause the padding error.
Thank you
As you said, I realized later that there is a file more than 80 classes. How can we increase this number?
