### ISSUE TITLE
No val_loss metric availibel on custom dataset. 

### ISSUE THREAD

**Issue by TheArchitect326** [zzh8829/yolov3-tf2#268]
When training on a custom dataset (I have converted the SVHN dataset to tfrecords). I get the following error after one epoch.

```python train.py --dataset ./data/train.tfrecord --val_dataset ./data/val.tfrecord --classes classes.names --num_classes 10 --mode fit --transfer darknet --batch_size 128 --epochs 300 --weights ./checkpoints/yolov3.tf --weights_num_classes 80
Epoch 1/300
2020-05-15 20:17:33.219724: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-05-15 20:17:33.221352: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
      1/Unknown - 21s 21s/step - loss: 6336.4600 - yolo_output_0_loss: 432.4231 - yolo_output_1_loss: 1303.6897 - yolo_output_2_loss: 4589.70362020-05-15 20:17:34.221113: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
    261/Unknown - 472s 2s/step - loss: 263.1074 - yolo_output_0_loss: 17.0192 - yolo_output_1_loss: 53.3328 - yolo_output_2_loss: 181.8405WARNING:tensorflow:Reduce LR on plateau conditioned on metric `val_loss` which is not available. Available metrics are: loss,yolo_output_0_loss,yolo_output_1_loss,yolo_output_2_loss,lr
W0515 20:25:18.520941 139666004383552 callbacks.py:1934] Reduce LR on plateau conditioned on metric `val_loss` which is not available. Available metrics are: loss,yolo_output_0_loss,yolo_output_1_loss,yolo_output_2_loss,lr
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,yolo_output_0_loss,yolo_output_1_loss,yolo_output_2_loss,lr
W0515 20:25:18.521471 139666004383552 callbacks.py:1286] Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,yolo_output_0_loss,yolo_output_1_loss,yolo_output_2_loss,lr

Epoch 00001: saving model to checkpoints/yolov3_train_1.tf
261/261 [==============================] - 489s 2s/step - loss: 263.1075 - yolo_output_0_loss: 17.0192 - yolo_output_1_loss: 53.3328 - yolo_output_2_loss: 181.8405
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    app.run(main)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 188, in main
    validation_data=val_dataset)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 825, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 395, in fit
    total_epochs=1)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 606, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:   indices[17] = [21, 15, 26, 2] does not index into shape [128,26,26,3,6]
	 [[{{node PartitionedCall_1/TensorScatterUpdate}}]]
	 [[IteratorGetNext]]
	 [[loss/yolo_output_0_loss/Shape_1/_12]]
  (1) Invalid argument:   indices[17] = [21, 15, 26, 2] does not index into shape [128,26,26,3,6]
	 [[{{node PartitionedCall_1/TensorScatterUpdate}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_53467]

Function call stack:
distributed_function -> distributed_function -> distributed_function -> distributed_function

WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-8
W0515 20:25:22.292993 139666004383552 util.py:144] Unresolved object in checkpoint: (root).layer-8
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-9
W0515 20:25:22.293236 139666004383552 util.py:144] Unresolved object in checkpoint: (root).layer-9
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-10
W0515 20:25:22.293357 139666004383552 util.py:144] Unresolved object in checkpoint: (root).layer-10
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-11
W0515 20:25:22.293469 139666004383552 util.py:144] Unresolved object in checkpoint: (root).layer-11
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
W0515 20:25:22.293650 139666004383552 util.py:152] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
```

I have read all similar issues and cannot seem to fix my problem.

Here is the code i wrote to create my tfrecord files.

```import hashlib
import os
from glob import glob
import tqdm
import h5py
import tensorflow as tf
from absl import app, flags, logging
from absl.flags import FLAGS
from PIL import Image
from pprint import pprint

flags.DEFINE_string('data_dir', './data', 'Directory to SVHN (format 1) folders')

def get_image_annotations(path, matfile):
    name = path.split('/')[-1].split('.')[0]
    annotation = {'name': name}
    item = matfile['digitStruct']['bbox'][int(name) - 1].item()

    for key in ['label', 'left', 'top', 'width', 'height']:
        attribute = matfile[item][key]
        values = [matfile[attribute[()][i].item()][()][0][0] for i in range(len(attribute))] if len(attribute) > 1 else [attribute[()][0][0]]
        annotation[key] = values

    with Image.open(path) as img:
        width, height = img.size

    return annotation, width, height


def build_example(path, matfile, classmap):
    img_raw = open(path, 'rb').read()
    key = hashlib.sha256(img_raw).hexdigest()

    annotation, width, height = get_image_annotations(path, matfile)

    xmin = [float(x) / width for x in annotation['left']]
    ymin = [float(y) / height for y in annotation['top']]
    xmax = [float(x + w) / width for x, w in zip(annotation['left'], annotation['width'])]
    ymax = [float(y + h) / height for y, h in zip(annotation['top'], annotation['height'])]
    classes_text = [str(int(label)).encode('utf8') for label in annotation['label']]
    classes = [classmap[str(int(label))] for label in annotation['label']]

    feature_dict={
        'image/height': tf.train.Feature(int64_list=tf.train.Int64List(value=[height])),
        'image/width': tf.train.Feature(int64_list=tf.train.Int64List(value=[width])),
        'image/filename': tf.train.Feature(bytes_list=tf.train.BytesList(value=[
                          annotation['name'].encode('utf8')])),
        'image/source_id': tf.train.Feature(bytes_list=tf.train.BytesList(value=[
                           annotation['name'].encode('utf8')])),
        'image/key/sha256': tf.train.Feature(bytes_list=tf.train.BytesList(value=[key.encode('utf8')])),
        'image/encoded': tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_raw])),
        'image/format': tf.train.Feature(bytes_list=tf.train.BytesList(value=['png'.encode('utf8')])),
        'image/object/bbox/xmin': tf.train.Feature(float_list=tf.train.FloatList(value=xmin)),
        'image/object/bbox/xmax': tf.train.Feature(float_list=tf.train.FloatList(value=xmax)),
        'image/object/bbox/ymin': tf.train.Feature(float_list=tf.train.FloatList(value=ymin)),
        'image/object/bbox/ymax': tf.train.Feature(float_list=tf.train.FloatList(value=ymax)),
        'image/object/class/text': tf.train.Feature(bytes_list=tf.train.BytesList(value=classes_text)),
        'image/object/class/label': tf.train.Feature(int64_list=tf.train.Int64List(value=classes)),
    }

    return tf.train.Example(features=tf.train.Features(feature=feature_dict))


def convert_split(inpath, outpath, classmap):
    writer = tf.io.TFRecordWriter(outpath)
    image_list = sorted(glob(os.path.join(inpath, '*.png')))
    logging.info(f'Image list loaded: {len(image_list)}')
    with h5py.File(os.path.join(inpath, 'digitStruct.mat'), 'r') as matfile:
        for image in tqdm.tqdm(image_list):
            tf_example = build_example(image, matfile, classmap)
            writer.write(tf_example.SerializeToString())

    writer.close()
    logging.info('Done')


def main(_):
    classmap = {name: idx for idx, name in enumerate(open('classes.names').read().splitlines())}
    print(classmap)
    convert_split(os.path.join(FLAGS.data_dir, 'train'), os.path.join(FLAGS.data_dir, 'train.tfrecord'), classmap)
    convert_split(os.path.join(FLAGS.data_dir, 'test'), os.path.join(FLAGS.data_dir, 'test.tfrecord'), classmap)
    convert_split(os.path.join(FLAGS.data_dir, 'extra'), os.path.join(FLAGS.data_dir, 'val.tfrecord'), classmap)


if __name__ == '__main__':
    app.run(main)
```

**Comment by TheArchitect326** [comment]
I have fixed this error.
I was assuming that the SVHN dataset was labeled correctly.
It turns out there a re a number of images with boxes that go outside of them.

**Comment by cypherix** [comment]
@TheArchitect326 What was the issue? I didnt understand. I am having the same error and can't seem to resolve it.

**Comment by MoisheKeselman** [comment]
@krxat I used the same data set and encountered the same issue. The problem is that some of the bounding boxes go outside of the image. Using something like `numpy.clip()` should fix the problem.
