### ISSUE TITLE
detect.py ERROR

### ISSUE THREAD

**Issue by CnybTseng** [zzh8829/yolov3-tf2#34]
python detect.py --weights ./checkpoints/yolov3-tiny.tf --tiny --image ./data/girl.png

W0706 03:01:45.838256 139645809293184 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-07-06 03:01:47.077830: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-07-06 03:01:47.078112: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x16d4a00 executing computations on platform Host. Devices:
2019-07-06 03:01:47.078146: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-06 03:01:47.158210: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
I0706 03:01:47.481413 139645809293184 detect.py:29] weights loaded
I0706 03:01:47.481828 139645809293184 detect.py:32] classes loaded
I0706 03:01:47.794163 139645809293184 detect.py:41] time: 0.30501627922058105
I0706 03:01:47.794389 139645809293184 detect.py:43] detections:
Traceback (most recent call last):
  File "detect.py", line 56, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "detect.py", line 44, in main
    for i in range(nums[0]):
TypeError: 'Tensor' object cannot be interpreted as an integer

**Comment by Pari-singh** [comment]
I am getting this error as well. Did you find any solution @CnybTseng

**Comment by Pari-singh** [comment]
I had this issue as well but then I realized it was because somewhere in the code I had used tf.compat.v1 to get the function from the version 1. Have a look if you are purely using TF v2.
