### ISSUE TITLE
Covert txt to tfrecord, train miss Error.

### ISSUE THREAD

**Issue by Rainweic** [zzh8829/yolov3-tf2#41]
I have a train.txt, like this:
```
# imagepath xmin,ymin,xmax,ymax,label ...
path/to/img1.jpg 50,100,150,200,0 30,50,200,120,3
path/to/img2.jpg 120,300,250,600,2
...
```

Then I covert this txt file to tfreord with this code:
```python
import os
import random
import tensorflow as tf

train_txt = './train.txt'
images_path = './JPEGImages'

def get_example(line):
    class_text = []
    xmin = []
    ymin = []
    xmax = []
    ymax = []

    line = line.split(' ')
    # 读取图片
    image_path = line[0]
    with tf.io.gfile.GFile(image_path, 'rb') as fib:
        image_encoded = fib.read()

    # 读取坐标及类别
    for item in line[1:]:
        item = item.split(',')
        xmin.append(float(item[0]))
        ymin.append(float(item[1]))
        xmax.append(float(item[2]))
        ymax.append(float(item[3]))
        if item[4] == 0:
            class_text.append("0".encode('utf8'))
        else:
            class_text.append("1".encode('utf8'))

    example = tf.train.Example(features=tf.train.Features(feature={
        'image/encoded': tf.train.Feature(bytes_list=tf.train.BytesList(value=[image_encoded])),
        'image/object/bbox/xmin': tf.train.Feature(float_list=tf.train.FloatList(value=xmin)),
        'image/object/bbox/xmax': tf.train.Feature(float_list=tf.train.FloatList(value=xmax)),
        'image/object/bbox/ymin': tf.train.Feature(float_list=tf.train.FloatList(value=ymin)),
        'image/object/bbox/ymax': tf.train.Feature(float_list=tf.train.FloatList(value=ymax)),
        'image/object/class/text': tf.train.Feature(bytes_list=tf.train.BytesList(value=class_text))
    }))

    return example

train_writer = tf.io.TFRecordWriter('./train.tfrecord')
val_writer = tf.io.TFRecordWriter('./val.tfrecord')
with open(train_txt, 'r') as f:
    lines = f.read().split('\n')
    random.shuffle(lines)
    # 训练数据
    for line in lines[:5000]:
        if len(line) > 0:
            example = get_example(line)
            train_writer.write(example.SerializeToString())
    # val数据
    for line in lines[5000:]:
        if len(line) > 0:
            example = get_example(line)
            val_writer.write(example.SerializeToString())
train_writer.close()
val_writer.close()
print("finish!")

``` 

and in yolov3_tf2/dataset.py, I have revised a little(line 79 ~ 97)：
```python
# https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md#conversion-script-outline-conversion-script-outline
IMAGE_FEATURE_MAP = {
    # 'image/width': tf.io.FixedLenFeature([], tf.int64),
    # 'image/height': tf.io.FixedLenFeature([], tf.int64),
    # 'image/filename': tf.io.FixedLenFeature([], tf.string),
    # 'image/source_id': tf.io.FixedLenFeature([], tf.string),
    # 'image/key/sha256': tf.io.FixedLenFeature([], tf.string),
    'image/encoded': tf.io.FixedLenFeature([], tf.string),
    # 'image/format': tf.io.FixedLenFeature([], tf.string),
    'image/object/bbox/xmin': tf.io.VarLenFeature(tf.float32),
    'image/object/bbox/ymin': tf.io.VarLenFeature(tf.float32),
    'image/object/bbox/xmax': tf.io.VarLenFeature(tf.float32),
    'image/object/bbox/ymax': tf.io.VarLenFeature(tf.float32),
    'image/object/class/text': tf.io.VarLenFeature(tf.string),
    # 'image/object/class/label': tf.io.VarLenFeature(tf.int64),
    # 'image/object/difficult': tf.io.VarLenFeature(tf.int64),
    # 'image/object/truncated': tf.io.VarLenFeature(tf.int64),
    # 'image/object/view': tf.io.VarLenFeature(tf.string),
}
```

when I begin to train, I miss this error:
```python
2019-07-26 09:28:12.864438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7134 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-07-26 09:28:27.838122: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at iterator_ops.cc:1055 : Invalid argument: Paddings must be non-negative: 0 -16
         [[{{node Pad}}]]
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    app.run(main)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 116, in main
    for batch, (images, labels) in enumerate(train_dataset):
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 586, in __next__
    return self.next()
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 623, in next
    return self._next_internal()
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 615, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2120, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -16
         [[{{node Pad}}]] [Op:IteratorGetNextSync]
Exception ignored in: <bound method _CheckpointRestoreCoordinator.__del__ of <tensorflow.python.training.tracking.util._CheckpointRestoreCoordinator object at 0x7f0c8052abe0>>
Traceback (most recent call last):
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/tracking/util.py", line 244, in __del__
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/tracking/util.py", line 93, in node_names
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/tracking/object_identity.py", line 76, in __getitem__
KeyError: (<tensorflow.python.training.tracking.object_identity._ObjectIdentityWrapper object at 0x7f0c8049a048>,)
```

Who can help me ? thanks！

**Comment by Rainweic** [comment]
I use this to train:
`python3 train.py --batch_size 8 --dataset ./train.tfrecord --val_dataset val.tfrecord --epochs 100 --mode eager_tf --transfer fine_tune`

**Comment by Rainweic** [comment]
I change the code witch is covert txt to tfrecord：
```python
import os
import hashlib
import random
import cv2 as cv
import tensorflow as tf

train_txt = './train.txt'
images_path = './JPEGImages'

def bytes_feature(value):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def bytes_list_feature(value):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))

def float_list_feature(value):
  return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def int64_feature(value):
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def int64_list_feature(value):
  return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def get_example(line):
    class_text = []
    labels = []
    xmin = []
    ymin = []
    xmax = []
    ymax = []
    truncated = []
    poses = []
    difficult_obj = []

    line = line.split(' ')

    # 读取图片
    image_path = line[0]
    with tf.io.gfile.GFile(image_path, 'rb') as fib:
        image_encoded = fib.read()
    h, w, _ = cv.imread(image_path).shape
    key = hashlib.sha256(image_encoded).hexdigest()

    # 读取坐标及类别
    for item in line[1:]:
        item = item.split(',')
        xmin.append(float(item[0]))
        ymin.append(float(item[1]))
        xmax.append(float(item[2]))
        ymax.append(float(item[3]))
        if item[4] == 0:
            class_text.append("0".encode('utf8'))
            labels.append(o)
        else:
            class_text.append("1".encode('utf8'))
            labels.append(1)
        truncated.append(0)
        difficult_obj.append(0)
        poses.append("Unspecified".encode('utf8'))

    example = tf.train.Example(features=tf.train.Features(feature={
      'image/height': int64_feature(h),
      'image/width': int64_feature(w),
      'image/filename': bytes_feature(image_path.encode('utf8')),
      'image/source_id': bytes_feature(image_path.encode('utf8')),
      'image/key/sha256': bytes_feature(key.encode('utf8')),
      'image/encoded': bytes_feature(image_encoded),
      'image/format': bytes_feature('jpeg'.encode('utf8')),
      'image/object/bbox/xmin': float_list_feature(xmin),
      'image/object/bbox/xmax': float_list_feature(xmax),
      'image/object/bbox/ymin': float_list_feature(ymin),
      'image/object/bbox/ymax': float_list_feature(ymax),
      'image/object/class/text': bytes_list_feature(class_text),
      'image/object/class/label': int64_list_feature(labels),
      'image/object/difficult': int64_list_feature(difficult_obj),
      'image/object/truncated': int64_list_feature(truncated),
      'image/object/view': bytes_list_feature(poses),
    }))

    return example

train_writer = tf.io.TFRecordWriter('./train.tfrecord')
val_writer = tf.io.TFRecordWriter('./val.tfrecord')
with open(train_txt, 'r') as f:
    lines = f.read().split('\n')
    random.shuffle(lines)
    # 训练数据
    for line in lines[:5000]:
        if len(line) > 0:
            example = get_example(line)
            train_writer.write(example.SerializeToString())
    # val数据
    for line in lines[5000:]:
        if len(line) > 0:
            example = get_example(line)
            val_writer.write(example.SerializeToString())
train_writer.close()
val_writer.close()
print("finish!")
```

and then I miss a new error when I train:
```python
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
2019-07-26 15:25:30.009322: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at iterator_ops.cc:1055 : Invalid argument: Paddings must be non-negative: 0 -62
	 [[{{node Pad}}]]
Traceback (most recent call last):
  File "train.py", line 178, in <module>
    app.run(main)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 173, in main
    validation_data=val_dataset)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 643, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/keras/engine/training_generator.py", line 694, in fit
    steps_name='steps_per_epoch')
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/keras/engine/training_generator.py", line 220, in model_iteration
    batch_data = _get_next_batch(generator, mode)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/keras/engine/training_generator.py", line 362, in _get_next_batch
    generator_output = next(generator)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 586, in __next__
    return self.next()
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 623, in next
    return self._next_internal()
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 615, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2120, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -62
	 [[{{node Pad}}]] [Op:IteratorGetNextSync]
2019-07-26 15:25:33.035865: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at scatter_nd_op.cc:217 : Invalid argument: indices[0] = [0, 1059, 513, 2] does not index into shape [8,13,13,3,6]
Exception ignored in: <bound method _CheckpointRestoreCoordinator.__del__ of <tensorflow.python.training.tracking.util._CheckpointRestoreCoordinator object at 0x7f188c44d278>>
Traceback (most recent call last):
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/tracking/util.py", line 244, in __del__
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/tracking/util.py", line 93, in node_names
  File "/home/rainweic/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/tracking/object_identity.py", line 76, in __getitem__
KeyError: (<tensorflow.python.training.tracking.object_identity._ObjectIdentityWrapper object at 0x7f16a0c33160>,)
```

**Comment by zzh8829** [comment]
the bounding box needs to be specified in percentage instead of pixels like this
`0.1 0.2 0.5 0.6`

**Comment by AnaRhisT94** [comment]
> ```python
> if item[4] == 0:
> ```

Change `if item[4] == 0:` to `if item[4] == "0"`, same in the next lines.
Also add an `else` check and throw an exception there.

**Comment by zzh8829** [comment]
check out https://github.com/zzh8829/yolov3-tf2/blob/master/docs/training_voc.md
