### ISSUE TITLE
Nan values at very beginning of training and wrong tensor shapes

### ISSUE THREAD

**Issue by schneider128k** [zzh8829/yolov3-tf2#51]
I have successfully used the code to train from scratch and also using the options `darknet` and `no_output` on several custom data sets. I have written a script that produces the tf records for training and validation.

When I try to train on a new dataset, I get `nan` values for the loss at the very beginning of training and also an error message that some tensor shapes do not match.  I am not sure what is wrong. I think that I correctly generate the tf records for training and validation (`eagle_train.record` and `eagle_test.record` in the run below) because everything worked fine for the other data sets that I tried previously.

I have also noticed that the shapes that do not index into shape `[8, 13, 13, 3, 6]` change each time I rerun the command for training.  In the run below, the wrong shape is `[2, 13, 5, 2]`, but in other runs I got shapes such as `[1, 15, 5, 2]` and `[7, 13, 5, 2]` even though I have not changed the code at all.

Does anybody have an idea what could be the cause for this behavior? Thanks a lot for your help!

```
     95/Unknown - 57s 600ms/step - loss: nan - yolo_output_0_loss: nan - yolo_output_1_loss: nan - yolo_output_2_loss: nan2019-08-12 14:01:02.722807: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at scatter_nd_op.cc:217 : Invalid argument: indices[2] = [2, 13, 5, 2] does not index into sha
pe [8,13,13,3,6]
```

Here is the complete trace:

```
(yolov3-tf2-master) C:\Users\Pawel Wocjan\Documents\ML\yolov3-tf2-master>python train.py --dataset ./data/eagle_train.record --val_dataset ./data/eagle_test.record --transfer darknet --mode fit --epochs 2
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-08-12 13:59:48.546377: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-08-12 13:59:48.626458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
2019-08-12 13:59:48.629067: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-08-12 13:59:48.630822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-12 13:59:48.633876: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-08-12 13:59:48.636530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
2019-08-12 13:59:48.638655: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-08-12 13:59:48.640399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-12 13:59:49.208639: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-12 13:59:49.211078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-08-12 13:59:49.212671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-08-12 13:59:49.214527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6280 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
W0812 14:00:03.033751  7376 deprecation.py:323] From C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\ops\array_ops.py:1340: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/2
2019-08-12 14:00:34.698461: I tensorflow/core/profiler/lib/profiler_session.cc:174] Profiler session started.
2019-08-12 14:00:34.700999: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'cupti64_100.dll'; dlerror: cupti64_100.dll not found
2019-08-12 14:00:34.703512: W tensorflow/core/profiler/lib/profiler_session.cc:182] Encountered error while starting profiler: Unavailable: CUPTI error: CUPTI could not be loaded or symbol could not be found.
      1/Unknown - 29s 29s/step - loss: nan - yolo_output_0_loss: nan - yolo_output_1_loss: nan - yolo_output_2_loss: nan2019-08-12 14:00:34.991461: I tensorflow/core/platform/default/device_tracer.cc:641] Collecting 0 kernel records, 0 memcpy records.
2019-08-12 14:00:35.036669: E tensorflow/core/platform/default/device_tracer.cc:68] CUPTI error: CUPTI could not be loaded or symbol could not be found.
     95/Unknown - 57s 600ms/step - loss: nan - yolo_output_0_loss: nan - yolo_output_1_loss: nan - yolo_output_2_loss: nan2019-08-12 14:01:02.722807: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at scatter_nd_op.cc:217 : Invalid argument: indices[2] = [2, 13, 5, 2] does not index into sha
pe [8,13,13,3,6]
     96/Unknown - 57s 597ms/step - loss: nan - yolo_output_0_loss: nan - yolo_output_1_loss: nan - yolo_output_2_loss: nan2019-08-12 14:01:02.768297: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at iterator_ops.cc:1055 : Invalid argument: [_Derived_]{{function_node __inference_transform_t
argets_for_output_14319_specialized_for_StatefulPartitionedCall_at___inference_Dataset_map_<lambda>_15243}} {{function_node __inference_transform_targets_for_output_14319_specialized_for_StatefulPartitionedCall_at___inference_Dataset_map_<lambda>_15243}} indices[2] = [2, 13, 5, 2] does not index into shape [8
,13,13,3,6]
         [[{{node TensorScatterUpdate}}]]
         [[StatefulPartitionedCall]]
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    app.run(main)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 188, in main
    validation_data=val_dataset)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\keras\engine\training.py", line 643, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 694, in fit
    steps_name='steps_per_epoch')
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 220, in model_iteration
    batch_data = _get_next_batch(generator, mode)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 362, in _get_next_batch
    generator_output = next(generator)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 586, in __next__
    return self.next()
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 623, in next
    return self._next_internal()
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 615, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2150, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: [_Derived_]{{function_node __inference_transform_targets_for_output_14319_specialized_for_StatefulPartitionedCall_at___inference_Dataset_map_<lambda>_15243}} {{function_node __inference_transform_targets_for_output_14319_specialized_for_StatefulPar
titionedCall_at___inference_Dataset_map_<lambda>_15243}} indices[2] = [2, 13, 5, 2] does not index into shape [8,13,13,3,6]
         [[{{node TensorScatterUpdate}}]]
         [[StatefulPartitionedCall]] [Op:IteratorGetNextSync]
Exception ignored in: <bound method _CheckpointRestoreCoordinator.__del__ of <tensorflow.python.training.tracking.util._CheckpointRestoreCoordinator object at 0x00000284600F3E10>>
Traceback (most recent call last):
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\training\tracking\util.py", line 244, in __del__
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\training\tracking\util.py", line 93, in node_names
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\training\tracking\object_identity.py", line 76, in __getitem__
KeyError: (<tensorflow.python.training.tracking.object_identity._ObjectIdentityWrapper object at 0x00000282E5DA0F60>,)
```

**Comment by schneider128k** [comment]
I used automatically generated data for training. The problem was that some of these automatically generated bounding boxes were tiny (when the objects were very far) and also that some of them were partially out of the images, that is, could some coordinates smaller than zero or larger than the width or height. After making sure that all bounding boxes are sufficiently large and all of them are entirely inside the image, I could train without any issues. 

I suspect that some numerical issues arose when the bounding boxes were too small or partially outside the image.

**Comment by hasslercastro** [comment]
@schneider128k I have a question regarding the way tf_records are built and the image size,
I'm using the [script ](https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py ) suggested to create my tf_records , the images have a resolution of 3300x2545 , 
        'image/height': dataset_util.int64_feature(3300),
        'image/width': dataset_util.int64_feature(2545 ),
x_min and y_min in my case are the upper left corner and x_max and y_max the lower right corner.

        xmins.append(float(box['x_min'] / width))
        xmaxs.append(float(box['x_max'] / width))
        ymins.append(float(box['y_min'] / height))
        ymaxs.append(float(box['y_max'] / height))

They are normalized by the script mentioned.

When I train I run the following line: 
python train.py --dataset ../train_record.record --val_dataset ../val_record.record --epochs 1 --batch_size 8  --classes ./data/mydataset.names --transfer [ fine_tune | not_output] 

I'm always getting NaN values in loss when training, so my question is:
The problem could be related with the way I built the tf_records ? Do you have any clue why I'm getting these nan values. I've to mention that the images are pretty big, and the bounding boxes are big too, they are lke 1/4 of the image.

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2019-09-19 10:33:47.979094: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 91 of 1024
2019-09-19 10:33:57.974557: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 186 of 1024
2019-09-19 10:34:08.028901: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 276 of 1024
2019-09-19 10:34:14.783509: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:162] Shuffle buffer filled.
2019-09-19 10:34:38.213367: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1483] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2019-09-19 10:34:39.614521: I tensorflow/core/profiler/lib/profiler_session.cc:174] Profiler session started.

      1/Unknown - 62s 62s/step - loss: nan - yolo_output_0_loss: 12.7921 - yolo_output_1_loss: 0.1305 - yolo_output_2_loss:      2/Unknown - 63s 31s/step - loss: nan - yolo_output_0_loss: nan - yolo_output_1_loss: nan - yolo_output_2_loss: nan     85/Unknown - 129s 2s/step - loss: nan - yolo_output_0_loss: nan - yolo_output_1_loss: nan - yolo_output_2_loss: nan
Epoch 00001: saving model to checkpoints/yolov3_train_1.tf
85/85 [==============================] - 148s 2s/step - loss: nan - yolo_output_0_loss: nan - yolo_output_1_loss: nan - yolo_output_2_loss: nan - val_loss: nan - val_yolo_output_0_loss: nan - val_yolo_output_1_loss: nan - val_yolo_output_2_loss:nan

Exception ignored in: <function _CheckpointRestoreCoordinator.__del__ at 0x7f2883396bf8>
Traceback (most recent call last):
  File "/home/hc/yolo_v3/yolov3-tf2/enviroment/yolito/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 244, in __del__
    .format(pretty_printer.node_names[node_id]))
  File "/home/hc/yolo_v3/yolov3-tf2/enviroment/yolito/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 93, in node_names
    path_to_root[node_id] + (child.local_name,))
  File "/home/hc/yolo_v3/yolov3-tf2/enviroment/yolito/lib/python3.7/site-packages/tensorflow/python/training/tracking/object_identity.py", line 76, in __getitem__
    return self._storage[self._wrap_key(key)]
KeyError: (<tensorflow.python.training.tracking.object_identity._ObjectIdentityWrapper object at 0x7f2691087630>,)

**Comment by AnaRhisT94** [comment]
@hasslercastro Hi, did you manage to solve the `nan` issues?

**Comment by hasslercastro** [comment]
@AnaRhisT94  yes,  there was a problem with the tfrecord generator file, make sure that your bounding boxes are correct, (xmin,ymin)  in my experience should be the upperleft corner and (xmax,ymax) the right bottom corner. After you have done the tfrecords would be nice if you check that everything has been saved correctly, by creating a new script and loading them.
https://www.tensorflow.org/tutorials/load_data/tfrecord#reading_a_tfrecord_file

Hope this helps,
