### ISSUE TITLE
Training own Data with Yolo 608x608

### ISSUE THREAD

**Issue by htzmedia** [zzh8829/yolov3-tf2#61]
If i try to train the model on my own Dataset, everything works great when i'm using a input size of 416x416, but when i try it with a resolution of 608x608 i get this error:
`Incompatible shapes: [1,19,19,3,1] vs. [1,13,13,3,1]`
 Any Ideas?

**Comment by VicariNishimura** [comment]
Hello, try to set grid_size to 19 when working with 608x608 images

**Comment by DeltaTesting** [comment]
I've not tried it yet, but when debugging for another issue I had i saw that the resize to 416x416 inside the dataset.py is hardcoded, so it ignores the '--size' flag in the train script when it loads the tfrecord dataset, but the train script resizes it again later on to the target size so i'm not sure.

If the solution proposed before doesn't help you, take a look at what i said, maybe is that.

**Comment by VicariNishimura** [comment]
Yes ofc, I added an argument "size" to some functions to replace the hardcoded 416 size and feed the flag in it, and deleted the other resize operation. But I think that if he have [1,19,19,3,1] tensors it's because it's already resized.

**Comment by htzmedia** [comment]
> Hello, try to set grid_size to 19 when working with 608x608 images

thanks, now it works! grid_size should be calculated by size//32 (608//32 = 19)

**Comment by hasslercastro** [comment]
pip install gast==0.2.2 solved the issue

**Comment by seakkas** [comment]
Hello,

I have images that 1280x720. Do you have any recommendations? How should I proceed?

**Comment by Daniel451** [comment]
@VicariNishimura @htzmedia @DeltaTesting would you be so kind to point me at the changes you've introduced?

I have adjusted...

https://github.com/zzh8829/yolov3-tf2/blob/4a11d93e133ba76b9f683c63187eb31c926e0363/yolov3_tf2/models.py#L30

...to match `FLAGS.size` and changed the grid size accordingly in lines 151 and 277...

https://github.com/zzh8829/yolov3-tf2/blob/4a11d93e133ba76b9f683c63187eb31c926e0363/yolov3_tf2/models.py#L151

https://github.com/zzh8829/yolov3-tf2/blob/4a11d93e133ba76b9f683c63187eb31c926e0363/yolov3_tf2/models.py#L277

...but still I have problems with the output having the wrong shape:

```
ValueError: Dimensions must be equal, but are 13 and 19 for 'loss/yolo_output_0_loss/sub_3' (op: 'Sub') with input shapes: [?,13,13,3,2], [19,19,1,2].
```

So clearly there is another line I missed that causes the old `13, 13` for `416x416` (416/32=13).

**Comment by htzmedia** [comment]
Hi, undo every change in models.py.
you have to change the grid_size only in dataset.py line 48. Just as I told it's 608/32 (32 because this is the stride of the network).

Line 30 in models.py is just for the anchor boxes they were made based on the COCO-Dataset. Maybe read the Yolo paper to learn more about it. But don't change the 416 value there.

**Comment by Daniel451** [comment]
@htzmedia that's interesting. Why should the grid sizes in the model's implementation stay unchanged if one wants to tweak the grid size and increase the resolution?

The vanilla setup should have 3 grids, the first 13x13 for detecting large objects, 26x26 for medium sized ones, and 52x52 for small ones. For each of the 3 grids, we should have 3 bounding box predictions, thus needing 9 anchors per cell.

If I change the resolution and adjust the grid sizes, it should also be changed in the model & loss?!

**Comment by htzmedia** [comment]
I am sorry of course you are right. I customized my anchor boxes.

For the anchor boxes you should create your own if you are not using the COCO Dataset.
like in the offical paper you could use k-means for that.

Than you have to change it in dataset.py grid_size = input_size / stride_of_network (= 32)

**Comment by ancoca13** [comment]
I'm having a similar issue but ussing the default image size.

When I execute the following:

`python train.py --dataset /home/box-ai/dataset/tfrecord/person_car_db_train.tfrecord --val_dataset /home/box-ai/dataset/tfrecord/person_car_db_val.tfrecord --epochs 1 --transfer fine_tune --num_classes 2`

I get:

`Traceback (most recent call last):
  File "train.py", line 180, in <module>
    app.run(main)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 77, in main
    model.load_weights(FLAGS.weights)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 181, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1149, in load_weights
    status = self._trackable_saver.restore(filepath)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/util.py", line 1270, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 908, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/util.py", line 289, in restore_saveables
    validated_saveables).restore(self.save_path_tensor)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/training/saving/functional_saver.py", line 255, in restore
    restore_ops.update(saver.restore(file_prefix))
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/training/saving/functional_saver.py", line 102, in restore
    restored_tensors, restored_shapes=None)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/training/saving/saveable_object_util.py", line 115, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 291, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/box-ai/anaconda3/envs/yolov3-tf2-cpu/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 1115, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (21,) and (255,) are incompatible`

**Comment by VicariNishimura** [comment]
This is because you load a pretrained model which have 80 classes, and you want to set weights for a model which have 2 classes.

**Comment by ancoca13** [comment]
> This is because you load a pretrained model which have 80 classes, and you want to set weights for a model which have 2 classes.

So it is not possible to use transfer training with a different number of classes than the pretrained model?

**Comment by VicariNishimura** [comment]
it is, but don't load classifier part weights, do something like :
```
# your model with 2 classes
my_model_80_classes = YoloV3(FLAGS.size, training=True, classes=2)
# load a 80 classes model
pretrained_model_80_classes = YoloV3(FLAGS.size, training=True, classes=80)

# load weights from a file with 80 classes (pretrained coco)
model_pretrained.load_weights(FLAGS.weights)

# load darknet weigths    my_model.get_layer('yolo_darknet').set_weights(model_pretrained.get_layer('yolo_darknet').get_weights())
```
