### ISSUE TITLE
Error when training on GPU: CUDNN_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by DeltaTesting** [zzh8829/yolov3-tf2#64]
I've got an error when trying to train on a GPU (I can train on a CPU)
I think i've the tensorflow-gpu 2.0 correctly installed since i'm able to run the minist example in my computer without any problem. ( https://colab.research.google.com/github/tensorflow/docs/blob/r2.0rc/site/en/r2/tutorials/quickstart/beginner.ipynb#scrollTo=F7dTAzgHDUh7 ).

I've also created a reduced dataset (only 2 images of size 800x600) in order to be sure that i'm not asking for more memory than i have. (my tdrecords have a size of less than a 1Mb)

And i've also executed the training script just after a system reboot to make sure I don't have any process of previous trainings.

For an extra information, I'm useing windows.

The stack trace:

`2019-09-05 17:25:59.832537: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2019-09-05 17:26:01.310588: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2019-09-05 17:26:01.313849: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    app.run(main)
  File "C:\Program Files\Python36\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Program Files\Python36\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 134, in main
    outputs = model(images, training=True)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 851, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 697, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 842, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 851, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 697, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 842, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 851, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\keras\layers\convolutional.py", line 197, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 1134, in __call__
    return self.conv_op(inp, filter)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 238, in __call__
    name=self.name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 2010, in conv2d
    name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1031, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1130, in conv2d_eager_fallback
    ctx=_ctx, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]`

Any ideas?

**Comment by zzh8829** [comment]
did you use conda to install tensorflow gpu, looks like environment is not setup properly

**Comment by DeltaTesting** [comment]
No, i've installed it manually with pip. I don't have conda installed.
I've just tried to execute it on an ubuntu machine with the docker image 'tensorflow/tensorflow:2.0.0rc0-gpu-py3' and 'nvidia-driver-435' and i got a similar error:
 `E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR`

**Comment by DeltaTesting** [comment]
I wrote the `tf.config.experimental.set_memory_growth(gpu, True)` into the main function. Moving it into the root of the file (before if __name__...) solved this issue.

**Comment by volkov-maxim** [comment]
Same error with convert.py:

I0306 07:29:20.160368  6296 **convert.py**:22] weights loaded
2020-03-06 07:29:20.198286: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-03-06 07:29:24.084445: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] **Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED**
2020-03-06 07:29:24.085882: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] **Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED**
...
Traceback (most recent call last):
  File "./convert.py", line 35, in <module>
    app.run(main)
  File "C:\Projects\FoodApp\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Projects\FoodApp\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./convert.py", line 25, in main
    output = yolo(img)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\keras\layers\convolutional.py", line 209, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 1135, in __call__
    return self.conv_op(inp, filter)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 640, in __call__
    return self.call(inp, filter)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 239, in __call__
    name=self.name)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 2011, in conv2d
    name=name)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 933, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1022, in conv2d_eager_fallback
    ctx=ctx, name=name)
  File "C:\Projects\FoodApp\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
**tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]**

I make the changes in convert.py:
1. At the beginning of the file: 
`import tensorflow as tf`
2. At the end of the file:
`if __name__ == '__main__':
    physical_devices = tf.config.list_physical_devices('GPU')
    try:
        tf.config.experimental.set_memory_growth(physical_devices[0], True)
        app.run(main)
    except SystemExit:
        pass`

Thanks to @DeltaTesting for help with set_memory_growth function and helpfull article: https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth
