### ISSUE TITLE
Paddings must be non-negative: 0 -19

### ISSUE THREAD

**Issue by tekotan** [zzh8829/yolov3-tf2#84]
I am using my own dataset that I generated using the script given in README. 

`Traceback (most recent call last):  File "train.py", line 180, in <module>    app.run(main)
  File "/home/tanish/yolov3-tf2/env/lib/python3.6/site-packages/absl/app.py", line 299, in run    _run_main(main, args)  File "/home/tanish/yolov3-tf2/env/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))  File "train.py", line 120, in main    for batch, (images, labels) in enumerate(train_dataset):  File "/home/tanish/yolov3-tf2/env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 622, in __next__    return self.next()  File "/home/tanish/yolov3-tf2/env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 666, in next
    return self._next_internal()
  File "/home/tanish/yolov3-tf2/env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 651, in _next_internal    output_shapes=self._flat_output_shapes)
  File "/home/tanish/yolov3-tf2/env/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2673, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_fromtensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_<lambda>_14279}} Paddings must be non-negative: 0 -19
         [[{{node Pad}}]] [Op:IteratorGetNextSync]`

Can someone help me with this?

**Comment by DeltaTesting** [comment]
how many outputs/detections can you have on a single image? (max)

**Comment by ancoca13** [comment]
I had that problem in two situations:
 - tfrecord bbox points not defined in range [0.0-1.0]
 - num_classes set to default when trying to train a model with a different number of classes than the pretrained

**Comment by ancoca13** [comment]
@tekotan, I have also noticed that when a image has more than 100 bounding boxes this error apears.
In your case maybe you have an image with 119 bounding boxes and the pad is defined as [0, 100 - number of bounding boxes]

**Comment by DeltaTesting** [comment]
To solve this you can change the pad with: [0, 200 - number of bounding boxes] for example

**Comment by zzh8829** [comment]
Hi i have added a new flag `yolo_max_boxes` to specify the maximum number of boxes in your dataset
